/**:
    ros__parameters:
      video_device: "/dev/video4"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "rondor_camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 720
      camera_name: "rondor_webcam"
      camera_info_url: "package://usb_cam/config/rondor_camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: true
      focus: -1
